version: '3.9'

services:
  employeemanagement.api:
    image: ${DOCKER_REGISTRY-}employeemanagementapi
    restart: always
    build:
      context: .
      dockerfile: EmployeeManagement.API/Dockerfile
    ports:
      - 54079:443
      - 54078:80
    depends_on: 
        - sql-server-db
  employeemanagement.payroll.api:
    image: ${DOCKER_REGISTRY-}employeemanagementpayrollapi
    restart: always
    build:
      context: .
      dockerfile: EmployeeManagement.PayRoll.API/Dockerfile
    ports:
      - 54081:443
      - 54080:80
    depends_on: 
        - sql-server-db
  employeemanagement.account.api:
    image: ${DOCKER_REGISTRY-}employeemanagementaccountapi
    restart: always
    build:
      context: .
      dockerfile: EmployeeManagement.Account.API/Dockerfile
    ports:
      - 54083:443
      - 54082:80
    depends_on: 
      - sql-server-db
  sql-server-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: SqlServerLatest
    restart: always
    ports:
        - 1433:1433    
    environment:
        SA_PASSWORD: "SecurePassword1"
        ACCEPT_EULA: "Y"
    volumes:
        - sql-server-data:/var/opt/mssql/

volumes:
    sql-server-data:
